openapi: 3.0.1
info:
  title: Najara.py
  description: 'Najara is a serverless Python/Flask based REST API for managing a collection of DND 5e items on AWS.'
  contact:
    email: greyshipscode@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about the author
  url: https://github.com/greynewell
tags:
- name: item
  description: Perform operations on a collection of items
  externalDocs:
    description: Find out more
    url: https://www.dndbeyond.com/magic-items
security:
  - BearerAuth: []
paths:
  /item:
    get:
      tags:
      - item
      summary: Returns a list of collections.
      description: Fetch all item collections stored in this instance of Najara.
      operationId: listCollections
      responses:
        200:
          description: Success response- the list of all item collections in Najara!
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Collection'
            application/xml:
              schema:
                $ref: '#/components/schemas/Collection'
  /item/{id}:
    post:
        tags:
        - item
        summary: Create an item in the collection with the given id.
        description: Provide the necessary properties of the item and a valid collection GUID.
        operationId: createCollection
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
            application/xml:
              schema:
                $ref: '#/components/schemas/Item'
        parameters:
        - name: id
          in: path
          description: GUID id of the collection you'd like to create. Will be generated if not specified.
          required: false
          schema:
            example: 'd66e22c7-95d2-49d2-95a2-77220a444411'
            type: string
        responses:
          200:
            description: Success response- your collection has been created!
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreateSuccess'
              application/xml:
                schema:
                  $ref: '#/components/schemas/CreateSuccess'
          404:
            description: No collection found for given id.
    get:
      tags:
      - item
      summary: Return a list of items belonging to a collection.
      description: Fetch all items from a Najara collection using its id.
      operationId: readCollection
      parameters:
      - name: id
        in: path
        description: The id key of the desired collection in GUID format
        required: true
        schema:
          example: 'd66e22c7-95d2-49d2-95a2-77220a444411'
          type: string
      responses:
        200:
          description: Success response- the items of your requested collection!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
            application/xml:
              schema:
                $ref: '#/components/schemas/Item'
        404:
          description: No collection found for the requested id.
    put:
        tags:
        - item
        summary: Add an item to a collection.
        description: Provide the properties of the new item and a valid collection GUID.
        operationId: updateCollection
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
            application/xml:
              schema:
                $ref: '#/components/schemas/Item'
        parameters:
        - name: id
          in: path
          description: GUID collection id where the item is to be added.
          required: true
          schema:
            example: 'd66e22c7-95d2-49d2-95a2-77220a444411'
            type: string
        responses:
          200:
            description: Success response- your item has been added to the collection!
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UpdateSuccess'
              application/xml:
                schema:
                  $ref: '#/components/schemas/UpdateSuccess'
          404:
            description: No collection found for the requested id.
    delete:
      tags:
      - item
      summary: Delete an item from a collection.
      description: Delete an item from a Najara collection using its id.
      operationId: deleteCollectionItem
      parameters:
      - name: id
        in: path
        description: The GUID of the collection to delete the item from
        required: true
        schema:
          example: 'd66e22c7-95d2-49d2-95a2-77220a444411'
          type: string
      - name: item-id
        in: path
        description: The id of the item to delete from the collection
        required: true
        schema:
           example: 135
           type: integer
      responses:
        200:
          description: Success response- your item has been deleted!
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/DeleteSuccess'
            application/xml:
              schema:
                $ref: '#/components/schemas/DeleteSuccess'
        404:
          description: Item not found. No Item could be found for the requested id.
components:
  securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 135
        name:
          type: string
          example: Arrows
        type:
          type: string
          example: Ammunition
        quantity:
          type: integer
          format: int64
          example: 1
        weight:
          minimum: 0
          type: number
          format: number
          example: 0.05
        gpvalue:
          minimum: 0
          type: number
          format: number
          example: 0.05
        description:
          type: string
          example: "A regular wooden arrow."
      xml:
        name: Item
    Collection:
      type: object
      properties:
        id:
          type: string
          format: GUID
          example: d66e22c7-95d2-49d2-95a2-77220a444411
        items:
          type: array
          items:
             $ref: '#/components/schemas/Item'
      xml:
        name: Collection
    ActionResult:
      type: object
      properties:
        status:
          type: string
          example: 'ACTION-STATUS: some-guid-of-requested-item'
      xml:
        name: ActionResult
    CreateSuccess:
      allOf:
        - $ref: '#/components/schemas/ActionResult'
        - type: object
          properties:
            status:
              type: string
              example: 'CREATE-SUCCESS: d66e22c7-95d2-49d2-95a2-77220a444411'
    UpdateSuccess:
      allOf:
        - $ref: '#/components/schemas/ActionResult'
        - type: object
          properties:
            status:
              type: string
              example: 'UPDATE-SUCCESS: d66e22c7-95d2-49d2-95a2-77220a444411'
    DeleteSuccess:
      allOf:
        - $ref: '#/components/schemas/ActionResult'
        - type: object
          properties:
            status:
              type: string
              example: 'DELETE-SUCCESS: d66e22c7-95d2-49d2-95a2-77220a444411'
